# Generated by Django 5.0.1 on 2024-02-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_Number',
            field=models.CharField(max_length=200),
        ),
    ]
